# Generated by Django 5.2.17 on 2026-09-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='last_opened_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
